#!/bin/sh

# Solution to Facebook engineering puzzle meepmeep
# http://www.facebook.com/careers/puzzles.php?puzzle_id=2
# Copyright (C) 2011 Jason Whittle <jason.whittle@gmail.com>
# Licensed under the terms of the GNU GPLv3

keyword=meepmeep
abspath=$(cd ${0%/*} && echo $PWD/${0##*/})
ruby $(dirname $abspath)/lib/$keyword.rb "$@"
